"""
Byline Translator
Converts Korean reporter names to English using mapping table
Total 543 mappings from seodaily_byline_data_translated_dedup_byline.xlsx
"""

# Reporter name mapping: Korean → English
REPORTER_NAME_MAP = {
    '(Commentary)': '(Commentary)',
    'AI PRISM': 'AI PRISM',
    'Ahn Hyun-duk (Commentary)': 'Ahn Hyun-duk (Commentary)',
    'Ahn Kyung-jin': 'Ahn Kyung-jin',
    'Ahn Kyung-jin (Commentary)': 'Ahn Kyung-jin (Commentary)',
    'Baeksang Forum (Commentary)': 'Baeksang Forum (Commentary)',
    'Chae Min-seok (Commentary)': 'Chae Min-seok (Commentary)',
    'Cho Dong-rye (Poetry)': 'Cho Dong-rye (Poetry)',
    'Cho Tae-hyung': 'Cho Tae-hyung',
    'Cho Yang-jun (Commentary)': 'Cho Yang-jun (Commentary)',
    'Choi Seung-hwan (Commentary)': 'Choi Seung-hwan (Commentary)',
    'Choi Soo-moon (Commentary)': 'Choi Soo-moon (Commentary)',
    'Decenter': 'Decenter',
    'Editorial Board (Commentary)': 'Editorial Board (Commentary)',
    'Editorial Board (Opinion)': 'Editorial Board (Opinion)',
    'Fareed Zakaria (Commentary)': 'Fareed Zakaria (Commentary)',
    'George Will (Commentary)': 'George Will (Commentary)',
    'Guest Contributor (Opinion)': 'Guest Contributor (Opinion)',
    'Han Dong-hoon': 'Han Dong-hoon',
    'Hong Ki-won': 'Hong Ki-won',
    'Jo Yang-jun (Commentary)': 'Jo Yang-jun (Commentary)',
    'Kim (Commentary)': 'Kim (Commentary)',
    'Kim Chang-young': 'Kim Chang-young',
    'Kim Chang-young (Commentary)': 'Kim Chang-young (Commentary)',
    'Kim Hye-ran': 'Kim Hye-ran',
    'Kim Hyun-ki (Commentary)': 'Kim Hyun-ki (Commentary)',
    'Kim Ji-young and Lee Jin-seok': 'Kim Ji-young and Lee Jin-seok',
    'Kim Ki-hyuk': 'Kim Ki-hyuk',
    'Kim Kwang-duk (Commentary)': 'Kim Kwang-duk (Commentary)',
    'Kim Kwang-soo (Commentary)': 'Kim Kwang-soo (Commentary)',
    'Kim Min-seok': 'Kim Min-seok',
    'Kim Seung-hyun (Commentary)': 'Kim Seung-hyun (Commentary)',
    'Kim So-young (Commentary)': 'Kim So-young (Commentary)',
    'Kim Su-ho': 'Kim Su-ho',
    'Kim Sung-tae (Commentary)': 'Kim Sung-tae (Commentary)',
    'Kim Tae-young': 'Kim Tae-young',
    'Kim Yoon-soo': 'Kim Yoon-soo',
    'Kim Young-wook (Opinion)': 'Kim Young-wook (Opinion)',
    'Ko Hak-soo (Commentary)': 'Ko Hak-soo (Commentary)',
    'Kook Kyung-bok (Commentary)': 'Kook Kyung-bok (Commentary)',
    'Lee Chung-hee (Commentary)': 'Lee Chung-hee (Commentary)',
    'Lee Dong-hwan': 'Lee Dong-hwan',
    'Lee Hyun-ho': 'Lee Hyun-ho',
    'Lee Hyun-ho (Commentary)': 'Lee Hyun-ho (Commentary)',
    'Lee Jin-seok': 'Lee Jin-seok',
    'Lee Jin-seok and Kim Ji-young': 'Lee Jin-seok and Kim Ji-young',
    'Lee Jong-hyeok (Commentary)': 'Lee Jong-hyeok (Commentary)',
    'Lee Jun': 'Lee Jun',
    'Lee Kyung-hwan': 'Lee Kyung-hwan',
    'Lee Moon-jung (Commentary)': 'Lee Moon-jung (Commentary)',
    'Lee Sang-chul (Commentary)': 'Lee Sang-chul (Commentary)',
    'Lee Seung-hun (Commentary)': 'Lee Seung-hun (Commentary)',
    'Lee So-hyun': 'Lee So-hyun',
    'Lee Tae-kyu': 'Lee Tae-kyu',
    'Lee Tae-kyu (Commentary)': 'Lee Tae-kyu (Commentary)',
    'Lee Won-jae (Commentary)': 'Lee Won-jae (Commentary)',
    'Lee Young-hwan (Commentary)': 'Lee Young-hwan (Commentary)',
    'Moon Ye-bin': 'Moon Ye-bin',
    'Na Ki-sam (Commentary)': 'Na Ki-sam (Commentary)',
    'Park Chang-gyu': 'Park Chang-gyu',
    'Park Hyung-jun': 'Park Hyung-jun',
    'Seoul Economic Daily': 'Seoul Economic Daily',
    'Seoul Economic Daily Editorial': 'Seoul Economic Daily Editorial',
    'Shin Joo-heui': 'Shin Joo-heui',
    'Sim Hyeok': 'Sim Hyeok',
    'Song Won-young': 'Song Won-young',
    'Staff Reporter': 'Staff Reporter',
    'Weekly Decenter': 'Weekly Decenter',
    'Weekly Sports': 'Weekly Sports',
    'Weekly Sports Team': 'Weekly Sports Team',
    'Yang Yu-jin (Commentary)': 'Yang Yu-jin (Commentary)',
    '가평=이경환 기자': 'Gapyeong - Lee Gyeong-Hwan',
    '강도림 기자': 'Kang Do-Rim',
    '강도림 기자,도혜원 기자': 'Kang Do-Rim, Do Hye-Won',
    '강도림 기자,이승령 기자': 'Kang Do-Rim, Lee Seung-Ryeong',
    '강동헌 기자': 'Kang Dong-Heon',
    '강동효 기자': 'Kang Dong-Hyo',
    '강동효 기자,박창규 기자': 'Kang Dong-Hyo, Park Chang-Gyu',
    '강동효 기자,박형윤 기자': 'Kang Dong-Hyo, Park Hyeong-Yun',
    '강신우 기자': 'Kang Sin-U',
    '강진=박지훈 기자': 'Gangjin - Park Ji-Hun',
    '거제=박종완 기자': 'Geoje - Park Jong-Wan',
    '경산=손성락 기자': 'Gyeongsan - Son Seong-Rak',
    '고광본 논설위원·선임기자': 'Ko Gwang-Bon (Editorial Writer), Seon Im',
    '고광본 선임기자': 'Ko Gwang-Bon (Senior Reporter)',
    '고성=박종완 기자': 'Goseong - Park Jong-Wan',
    '고양=김성태 기자': 'Goyang - Kim Seong-Tae',
    '고양=이경환 기자': 'Goyang - Lee Gyeong-Hwan',
    '공준호 기자': 'Gong Jun-Ho',
    '공준호 기자,김우보 기자': 'Gong Jun-Ho, Kim U-Bo',
    '공준호 기자,임주형 기자': 'Gong Jun-Ho, Im Ju-Hyeong',
    '과천=박정훈 기자': 'Gwacheon - Park Jeong-Hun',
    '광명=박종완 기자': 'Gwangmyeong - Park Jong-Wan',
    '광양=손성락 기자': 'Gwangyang - Son Seong-Rak',
    '광주=박세환 기자': 'Gwangju - Park Se-Hwan',
    '광주=손성락 기자': 'Gwangju - Son Seong-Rak',
    '구미=최종권 기자': 'Gumi - Choi Jong-Gwon',
    '구정모 기자': 'Gu Jeong-Mo',
    '군산=홍석천 기자': 'Gunsan - Hong Seok-Cheon',
    '김강호 기자': 'Kim Gang-Ho',
    '김광수 기자': 'Kim Gwang-Su',
    '김기욱 기자': 'Kim Gi-Uk',
    '김기욱 기자,오장균 기자': 'Kim Gi-Uk, Oh Jang-Gyun',
    '김남준 기자': 'Kim Nam-Jun',
    '김남준 기자,박민주 기자': 'Kim Nam-Jun, Park Min-Ju',
    '김남준 기자,정다은 기자': 'Kim Nam-Jun, Jung Da-Eun',
    '김도현 기자': 'Kim Do-Hyeon',
    '김동현 기자': 'Kim Dong-Hyeon',
    '김도현 기자,김상수 기자': 'Kim Do-Hyeon, Kim Sang-Su',
    '김도현 기자,정다은 기자': 'Kim Do-Hyeon, Jung Da-Eun',
    '김명한 기자': 'Kim Myeong-Han',
    '김민권 기자': 'Kim Min-Gwon',
    '김상수 기자': 'Kim Sang-Su',
    '김상수 기자,김도현 기자': 'Kim Sang-Su, Kim Do-Hyeon',
    '김상수 기자,정다은 기자': 'Kim Sang-Su, Jung Da-Eun',
    '김성현 기자': 'Kim Seong-Hyeon',
    '김성현 기자,문예빈 기자': 'Kim Seong-Hyeon, Moon Ye-Bin',
    '김성현 기자,박준석 기자': 'Kim Seong-Hyeon, Park Jun-Seok',
    '김성현 기자,박형준 기자': 'Kim Seong-Hyeon, Park Hyeong-Jun',
    '김성환 기자': 'Kim Seong-Hwan',
    '김소연 기자': 'Kim So-Yeon',
    '김소영 기자': 'Kim So-Young',
    '김수호 기자': 'Kim Su-Ho',
    '김승현 기자': 'Kim Seung-Hyeon',
    '김영주 기자': 'Kim Yeong-Ju',
    '김영주 기자,김소연 기자': 'Kim Yeong-Ju, Kim So-Yeon',
    '김영주 기자,이은주 기자': 'Kim Yeong-Ju, Lee Eun-Ju',
    '김용호 기자': 'Kim Yong-Ho',
    '김우보 기자': 'Kim U-Bo',
    '김우보 기자,공준호 기자': 'Kim U-Bo, Gong Jun-Ho',
    '김우보 기자,문예빈 기자': 'Kim U-Bo, Moon Ye-Bin',
    '김우보 기자,서지혜 기자': 'Kim U-Bo, Seo Ji-Hye',
    '김원규 기자': 'Kim Won-Gyu',
    '김유리 기자': 'Kim Yu-Ri',
    '김윤수 기자': 'Kim Yun-Su',
    '김윤수 기자,이민구 기자': 'Kim Yun-Su, Lee Min-Gu',
    '김윤수 기자,한종수 기자': 'Kim Yun-Su, Han Jong-Su',
    '김은정 기자': 'Kim Eun-Jeong',
    '김정겸 기자': 'Kim Jeong-Gyeom',
    '김지영 기자': 'Kim Ji-Young',
    '김지영 기자,이진석 기자': 'Kim Ji-Young, Lee Jin-Seok',
    '김창년 기자': 'Kim Chang-Nyeon',
    '김태균 기자': 'Kim Tae-Gyun',
    '김태형 기자': 'Kim Tae-Hyeong',
    '김혜수 기자': 'Kim Hye-Su',
    '김형주 기자': 'Kim Hyeong-Ju',
    '남궁민관 기자': 'Namgoong Min-Gwan',
    '노정동 기자': 'Noh Jeong-Dong',
    '노정동 기자,윤혜진 기자': 'Noh Jeong-Dong, Yun Hye-Jin',
    '대전=박정훈 기자': 'Daejeon - Park Jeong-Hun',
    '도혜원 기자': 'Do Hye-Won',
    '도혜원 기자,강도림 기자': 'Do Hye-Won, Kang Do-Rim',
    '도혜원 기자,박민주 기자': 'Do Hye-Won, Park Min-Ju',
    '도혜원 기자,박성준 기자': 'Do Hye-Won, Park Seong-Jun',
    '도혜원 기자,이상철 기자': 'Do Hye-Won, Lee Sang-Cheol',
    '류재은 기자': 'Ryu Jae-Eun',
    '목포=손성락 기자': 'Mokpo - Son Seong-Rak',
    '문예빈 기자': 'Moon Ye-Bin',
    '문예빈 기자,김성현 기자': 'Moon Ye-Bin, Kim Seong-Hyeon',
    '문예빈 기자,김우보 기자': 'Moon Ye-Bin, Kim U-Bo',
    '문예빈 기자,박민주 기자': 'Moon Ye-Bin, Park Min-Ju',
    '문예빈 기자,박준석 기자': 'Moon Ye-Bin, Park Jun-Seok',
    '문예빈 기자,박형윤 기자': 'Moon Ye-Bin, Park Hyeong-Yun',
    '문예빈 기자,안세미 기자': 'Moon Ye-Bin, An Se-Mi',
    '문예빈 기자,임세은 기자': 'Moon Ye-Bin, Im Se-Eun',
    '문예빈 기자,정유민 기자': 'Moon Ye-Bin, Jung Yu-Min',
    '문예빈 기자,조이슬 기자': 'Moon Ye-Bin, Jo I-Seul',
    '박경훈 기자': 'Park Gyeong-Hun',
    '박경훈 기자,이현빈 기자': 'Park Gyeong-Hun, Lee Hyeon-Bin',
    '박민주 기자': 'Park Min-Ju',
    '박민주 기자,김남준 기자': 'Park Min-Ju, Kim Nam-Jun',
    '박민주 기자,도혜원 기자': 'Park Min-Ju, Do Hye-Won',
    '박민주 기자,문예빈 기자': 'Park Min-Ju, Moon Ye-Bin',
    '박민주 기자,변민주 기자': 'Park Min-Ju, Byun Min-Ju',
    '박민주 기자,이소윤 기자': 'Park Min-Ju, Lee So-Yun',
    '박민주 기자,정다은 기자': 'Park Min-Ju, Jung Da-Eun',
    '박민주 기자,정유민 기자': 'Park Min-Ju, Jung Yu-Min',
    '박성우 기자': 'Park Seong-U',
    '박성준 기자': 'Park Seong-Jun',
    '박성준 기자,도혜원 기자': 'Park Seong-Jun, Do Hye-Won',
    '박성준 기자,이소현 기자': 'Park Seong-Jun, Lee So-Hyeon',
    '박성준 기자,이시은 기자': 'Park Seong-Jun, Lee Si-Eun',
    '박성준 기자,조이슬 기자': 'Park Seong-Jun, Jo I-Seul',
    '박세환 기자': 'Park Se-Hwan',
    '박준석 기자': 'Park Jun-Seok',
    '박준석 기자,김성현 기자': 'Park Jun-Seok, Kim Seong-Hyeon',
    '박준석 기자,문예빈 기자': 'Park Jun-Seok, Moon Ye-Bin',
    '박준석 기자,안세미 기자': 'Park Jun-Seok, An Se-Mi',
    '박지윤 기자': 'Park Ji-Yun',
    '박지훈 기자': 'Park Ji-Hun',
    '박창규 기자': 'Park Chang-Gyu',
    '박창규 기자,강동효 기자': 'Park Chang-Gyu, Kang Dong-Hyo',
    '박창규 기자,박형윤 기자': 'Park Chang-Gyu, Park Hyeong-Yun',
    '박창규 기자,윤예원 기자': 'Park Chang-Gyu, Yun Ye-Won',
    '박형윤 기자': 'Park Hyeong-Yun',
    '박형윤 기자,강동효 기자': 'Park Hyeong-Yun, Kang Dong-Hyo',
    '박형윤 기자,문예빈 기자': 'Park Hyeong-Yun, Moon Ye-Bin',
    '박형윤 기자,박창규 기자': 'Park Hyeong-Yun, Park Chang-Gyu',
    '박형윤 기자,안세미 기자': 'Park Hyeong-Yun, An Se-Mi',
    '박형윤 기자,이민구 기자': 'Park Hyeong-Yun, Lee Min-Gu',
    '박형윤 기자,임주형 기자': 'Park Hyeong-Yun, Im Ju-Hyeong',
    '박형준 기자': 'Park Hyeong-Jun',
    '박형준 기자,김성현 기자': 'Park Hyeong-Jun, Kim Seong-Hyeon',
    '박형준 기자,심세훈 기자': 'Park Hyeong-Jun, Sim Se-Hun',
    '박형준 기자,양정훈 기자': 'Park Hyeong-Jun, Yang Jeong-Hun',
    '박형준 기자,정다은 기자': 'Park Hyeong-Jun, Jung Da-Eun',
    '반석=박정훈 기자': 'Banseok - Park Jeong-Hun',
    '변민주 기자': 'Byun Min-Ju',
    '변민주 기자,박민주 기자': 'Byun Min-Ju, Park Min-Ju',
    '변수연 기자': 'Byun Su-Yeon',
    '변수연 기자,워싱턴=이태규 특파원': 'Byun Su-Yeon, Washington - Lee Tae-Gyu (Correspondent)',
    '변수연 기자,이현호 기자': 'Byun Su-Yeon, Lee Hyeon-Ho',
    '부산=박종완 기자': 'Busan - Park Jong-Wan',
    '부산=최종권 기자': 'Busan - Choi Jong-Gwon',
    '서울경제': 'Seoul Economic Daily',
    '서지혜 기자': 'Seo Ji-Hye',
    '서지혜 기자,김우보 기자': 'Seo Ji-Hye, Kim U-Bo',
    '서지혜 기자,이민구 기자': 'Seo Ji-Hye, Lee Min-Gu',
    '서지혜 기자,이현호 기자': 'Seo Ji-Hye, Lee Hyeon-Ho',
    '성남=박정훈 기자': 'Seongnam - Park Jeong-Hun',
    '세종=이재민 기자': 'Sejong - Lee Jae-Min',
    '세종=임현우 기자': 'Sejong - Lim Hyeon-U',
    '세종=정인설 기자': 'Sejong - Jung In-Seol',
    '세종=최종권 기자': 'Sejong - Choi Jong-Gwon',
    '세종=홍성환 기자': 'Sejong - Hong Seong-Hwan',
    '손성락 기자': 'Son Seong-Rak',
    '손석우 기자': 'Son Seok-U',
    '송주희 기자': 'Song Ju-Hui',
    '송주희 기자,워싱턴=이태규 특파원': 'Song Ju-Hui, Washington - Lee Tae-Gyu (Correspondent)',
    '순천=박지훈 기자': 'Suncheon - Park Ji-Hun',
    '신서희 기자': 'Shin Seo-Hui',
    '신서희 기자,신주희 기자': 'Shin Seo-Hui, Shin Ju-Hui',
    '신주희 기자': 'Shin Ju-Hui',
    '신주희 기자,신서희 기자': 'Shin Ju-Hui, Shin Seo-Hui',
    '신현우 기자': 'Shin Hyeon-U',
    '심세훈 기자': 'Sim Se-Hun',
    '심세훈 기자,박형준 기자': 'Sim Se-Hun, Park Hyeong-Jun',
    '심세훈 기자,이현호 기자': 'Sim Se-Hun, Lee Hyeon-Ho',
    '안산=박정훈 기자': 'Ansan - Park Jeong-Hun',
    '안세미 기자': 'An Se-Mi',
    '안세미 기자,문예빈 기자': 'An Se-Mi, Moon Ye-Bin',
    '안세미 기자,박준석 기자': 'An Se-Mi, Park Jun-Seok',
    '안세미 기자,박형윤 기자': 'An Se-Mi, Park Hyeong-Yun',
    '안성=박종완 기자': 'Anseong - Park Jong-Wan',
    '안양=박종완 기자': 'Anyang - Park Jong-Wan',
    '양정훈 기자': 'Yang Jeong-Hun',
    '양정훈 기자,박형준 기자': 'Yang Jeong-Hun, Park Hyeong-Jun',
    '양정훈 기자,이현호 기자': 'Yang Jeong-Hun, Lee Hyeon-Ho',
    '여수=손성락 기자': 'Yeosu - Son Seong-Rak',
    '여수=홍석천 기자': 'Yeosu - Hong Seok-Cheon',
    '여주=이경환 기자': 'Yeoju - Lee Gyeong-Hwan',
    '연천=박정훈 기자': 'Yeoncheon - Park Jeong-Hun',
    '오장균 기자': 'Oh Jang-Gyun',
    '오장균 기자,김기욱 기자': 'Oh Jang-Gyun, Kim Gi-Uk',
    '왕승현 기자': 'Wang Seung-Hyeon',
    '용산=박정훈 기자': 'Yongsan - Park Jeong-Hun',
    '용인=박정훈 기자': 'Yongin - Park Jeong-Hun',
    '울산=박종완 기자': 'Ulsan - Park Jong-Wan',
    '울산=최종권 기자': 'Ulsan - Choi Jong-Gwon',
    '원주=박종완 기자': 'Wonju - Park Jong-Wan',
    '유주희 기자': 'Yu Ju-Hui',
    '유주희 기자,워싱턴=이태규 특파원': 'Yu Ju-Hui, Washington - Lee Tae-Gyu (Correspondent)',
    '윤예원 기자': 'Yun Ye-Won',
    '윤예원 기자,박창규 기자': 'Yun Ye-Won, Park Chang-Gyu',
    '윤혜진 기자': 'Yun Hye-Jin',
    '윤혜진 기자,노정동 기자': 'Yun Hye-Jin, Noh Jeong-Dong',
    '이경환 기자': 'Lee Gyeong-Hwan',
    '이규민 기자': 'Lee Gyu-Min',
    '이다솜 기자': 'Lee Da-Som',
    '이동환 기자': 'Lee Dong-Hwan',
    '이명우 기자': 'Lee Myeong-U',
    '이민구 기자': 'Lee Min-Gu',
    '이민구 기자,김윤수 기자': 'Lee Min-Gu, Kim Yun-Su',
    '이민구 기자,박형윤 기자': 'Lee Min-Gu, Park Hyeong-Yun',
    '이민구 기자,서지혜 기자': 'Lee Min-Gu, Seo Ji-Hye',
    '이민구 기자,이현호 기자': 'Lee Min-Gu, Lee Hyeon-Ho',
    '이보영 기자': 'Lee Bo-Yeong',
    '이상철 기자': 'Lee Sang-Cheol',
    '이상철 기자,도혜원 기자': 'Lee Sang-Cheol, Do Hye-Won',
    '이상철 기자,이소현 기자': 'Lee Sang-Cheol, Lee So-Hyeon',
    '이상철 기자,임주형 기자': 'Lee Sang-Cheol, Im Ju-Hyeong',
    '이상철 기자,정유민 기자': 'Lee Sang-Cheol, Jung Yu-Min',
    '이서영 기자': 'Lee Seo-Yeong',
    '이석원 기자': 'Lee Seok-Won',
    '이성규 기자': 'Lee Seong-Gyu',
    '이성희 기자': 'Lee Seong-Hui',
    '이소연 기자': 'Lee So-Yeon',
    '이소윤 기자': 'Lee So-Yun',
    '이소윤 기자,박민주 기자': 'Lee So-Yun, Park Min-Ju',
    '이소윤 기자,이시은 기자': 'Lee So-Yun, Lee Si-Eun',
    '이소현 기자': 'Lee So-Hyeon',
    '이소현 기자,강도림 기자': 'Lee So-Hyeon, Kang Do-Rim',
    '이소현 기자,박성준 기자': 'Lee So-Hyeon, Park Seong-Jun',
    '이소현 기자,이상철 기자': 'Lee So-Hyeon, Lee Sang-Cheol',
    '이송렬 기자': 'Lee Song-Ryeol',
    '이수지 기자': 'Lee Su-Ji',
    '이승령 기자': 'Lee Seung-Ryeong',
    '이승령 기자,강도림 기자': 'Lee Seung-Ryeong, Kang Do-Rim',
    '이시은 기자': 'Lee Si-Eun',
    '이시은 기자,박성준 기자': 'Lee Si-Eun, Park Seong-Jun',
    '이시은 기자,이소윤 기자': 'Lee Si-Eun, Lee So-Yun',
    '이시은 기자,조이슬 기자': 'Lee Si-Eun, Jo I-Seul',
    '이연주 기자': 'Lee Yeon-Ju',
    '이은주 기자': 'Lee Eun-Ju',
    '이은주 기자,김영주 기자': 'Lee Eun-Ju, Kim Yeong-Ju',
    '이재민 기자': 'Lee Jae-Min',
    '이정민 기자': 'Lee Jeong-Min',
    '이정은 기자': 'Lee Jeong-Eun',
    '이정인 기자': 'Lee Jeong-In',
    '이종호 기자': 'Lee Jong-Ho',
    '이준범 기자': 'Lee Jun-Beom',
    '이진석 기자': 'Lee Jin-Seok',
    '이진석 기자,김지영 기자': 'Lee Jin-Seok, Kim Ji-Young',
    '이철희 기자': 'Lee Cheol-Hui',
    '이태규 기자': 'Lee Tae-Gyu',
    '이하늘 기자': 'Lee Ha-Neul',
    '이한나 기자': 'Lee Han-Na',
    '이현빈 기자': 'Lee Hyeon-Bin',
    '이현빈 기자,박경훈 기자': 'Lee Hyeon-Bin, Park Gyeong-Hun',
    '이현빈 기자,임주형 기자': 'Lee Hyeon-Bin, Im Ju-Hyeong',
    '이현빈 기자,정유민 기자': 'Lee Hyeon-Bin, Jung Yu-Min',
    '이현호 기자': 'Lee Hyeon-Ho',
    '이현호 기자,변수연 기자': 'Lee Hyeon-Ho, Byun Su-Yeon',
    '이현호 기자,서지혜 기자': 'Lee Hyeon-Ho, Seo Ji-Hye',
    '이현호 기자,심세훈 기자': 'Lee Hyeon-Ho, Sim Se-Hun',
    '이현호 기자,양정훈 기자': 'Lee Hyeon-Ho, Yang Jeong-Hun',
    '이현호 기자,이민구 기자': 'Lee Hyeon-Ho, Lee Min-Gu',
    '임세은 기자': 'Im Se-Eun',
    '임세은 기자,문예빈 기자': 'Im Se-Eun, Moon Ye-Bin',
    '임세은 기자,정유민 기자': 'Im Se-Eun, Jung Yu-Min',
    '임세은 기자,조이슬 기자': 'Im Se-Eun, Jo I-Seul',
    '임주형 기자': 'Im Ju-Hyeong',
    '임주형 기자,공준호 기자': 'Im Ju-Hyeong, Gong Jun-Ho',
    '임주형 기자,박형윤 기자': 'Im Ju-Hyeong, Park Hyeong-Yun',
    '임주형 기자,이상철 기자': 'Im Ju-Hyeong, Lee Sang-Cheol',
    '임주형 기자,이현빈 기자': 'Im Ju-Hyeong, Lee Hyeon-Bin',
    '임현우 기자': 'Lim Hyeon-U',
    '전주=박세환 기자': 'Jeonju - Park Se-Hwan',
    '정다은 기자': 'Jung Da-Eun',
    '정다은 기자,김남준 기자': 'Jung Da-Eun, Kim Nam-Jun',
    '정다은 기자,김도현 기자': 'Jung Da-Eun, Kim Do-Hyeon',
    '정다은 기자,김상수 기자': 'Jung Da-Eun, Kim Sang-Su',
    '정다은 기자,박민주 기자': 'Jung Da-Eun, Park Min-Ju',
    '정다은 기자,박형준 기자': 'Jung Da-Eun, Park Hyeong-Jun',
    '정인설 기자': 'Jung In-Seol',
    '정유민 기자': 'Jung Yu-Min',
    '정유민 기자,문예빈 기자': 'Jung Yu-Min, Moon Ye-Bin',
    '정유민 기자,박민주 기자': 'Jung Yu-Min, Park Min-Ju',
    '정유민 기자,이상철 기자': 'Jung Yu-Min, Lee Sang-Cheol',
    '정유민 기자,이현빈 기자': 'Jung Yu-Min, Lee Hyeon-Bin',
    '정유민 기자,임세은 기자': 'Jung Yu-Min, Im Se-Eun',
    '정인설 기자,세종': 'Jung In-Seol, Sejong',
    '제천=박정훈 기자': 'Jecheon - Park Jeong-Hun',
    '제천=이경환 기자': 'Jecheon - Lee Gyeong-Hwan',
    '조성희 기자': 'Jo Seong-Hui',
    '조이슬 기자': 'Jo I-Seul',
    '조이슬 기자,문예빈 기자': 'Jo I-Seul, Moon Ye-Bin',
    '조이슬 기자,박성준 기자': 'Jo I-Seul, Park Seong-Jun',
    '조이슬 기자,이시은 기자': 'Jo I-Seul, Lee Si-Eun',
    '조이슬 기자,임세은 기자': 'Jo I-Seul, Im Se-Eun',
    '조지훈 기자': 'Jo Ji-Hun',
    '진주=손성락 기자': 'Jinju - Son Seong-Rak',
    '진주=박세환 기자': 'Jinju - Park Se-Hwan',
    '진천=박정훈 기자': 'Jincheon - Park Jeong-Hun',
    '창원=박종완 기자': 'Changwon - Park Jong-Wan',
    '창원=손성락 기자': 'Changwon - Son Seong-Rak',
    '천안=박정훈 기자': 'Cheonan - Park Jeong-Hun',
    '청주=박정훈 기자': 'Cheongju - Park Jeong-Hun',
    '최서윤 기자': 'Choi Seo-Yun',
    '최종권 기자': 'Choi Jong-Gwon',
    '춘천=박정훈 기자': 'Chuncheon - Park Jeong-Hun',
    '통영=박종완 기자': 'Tongyeong - Park Jong-Wan',
    '평택=이경환 기자': 'Pyeongtaek - Lee Gyeong-Hwan',
    '평택=박정훈 기자': 'Pyeongtaek - Park Jeong-Hun',
    '포천=박정훈 기자': 'Pocheon - Park Jeong-Hun',
    '포항=최종권 기자': 'Pohang - Choi Jong-Gwon',
    '한종수 기자': 'Han Jong-Su',
    '한종수 기자,김윤수 기자': 'Han Jong-Su, Kim Yun-Su',
    '홍석천 기자': 'Hong Seok-Cheon',
    '홍성환 기자': 'Hong Seong-Hwan',
    '화성=박종완 기자': 'Hwaseong - Park Jong-Wan',
    '화천=박정훈 기자': 'Hwacheon - Park Jeong-Hun',
    '글·사진(워싱턴)=이태규 특파원,서지혜 기자': 'Geul, Sajin(wosingteon) - Lee Tae-Gyu (Correspondent), Seo Ji-Hye',
    '워싱턴=이태규 특파원': 'Washington - Lee Tae-Gyu (Correspondent)',
    '워싱턴=이태규 특파원,베이징=김광수 특파원': 'Washington - Lee Tae-Gyu (Correspondent), Beijing - Kim Gwang-Su (Correspondent)',
    '워싱턴=이태규 특파원,이현호 기자': 'Washington - Lee Tae-Gyu (Correspondent), Lee Hyeon-Ho',
    '워싱턴=이태규 특파원,정다은 기자': 'Washington - Lee Tae-Gyu (Correspondent), Jung Da-Eun',
}


def translate_byline(byline: str) -> str:
    """
    Translate Korean reporter name to English

    Args:
        byline: Korean byline (e.g., "김우보 기자", "워싱턴=이태규 특파원")

    Returns:
        English byline (e.g., "Kim U-Bo", "Washington - Lee Tae-Gyu (Correspondent)")
        Falls back to "Seoul Economic Daily" if not found
    """
    if not byline or not byline.strip():
        return "Seoul Economic Daily"

    byline = byline.strip()

    # Try direct lookup in mapping table
    if byline in REPORTER_NAME_MAP:
        return REPORTER_NAME_MAP[byline]

    # If not found, return default
    return "Seoul Economic Daily"


if __name__ == "__main__":
    # Test cases
    test_cases = [
        ("김우보 기자", "Kim U-Bo"),
        ("워싱턴=이태규 특파원", "Washington - Lee Tae-Gyu (Correspondent)"),
        ("Seoul Economic Daily", "Seoul Economic Daily"),
        ("Staff Reporter", "Staff Reporter"),
        ("", "Seoul Economic Daily"),
        ("Unknown Reporter", "Seoul Economic Daily"),
    ]

    print("=== Byline Translation Tests ===\n")
    for korean, expected in test_cases:
        result = translate_byline(korean)
        status = "✅" if result == expected else "❌"
        print(f"{status} Input: '{korean}'")
        print(f"   Output: {result}")
        print(f"   Expected: {expected}\n")
