/**
 * 한글 기자 이름 → 영어 이름 매핑 테이블
 * 새로운 기자가 추가되면 여기에 추가하세요
 */
export const REPORTER_NAME_MAP: Record<string, string> = {
  // ㄱ
  '강도림': 'Do-rim Kang',
  '강동헌': 'Dong-heon Kang',
  '강동효': 'Dong-hyo Kang',
  '공준호': 'Jun-ho Gong',
  '구경우': 'Gyeong-u Gu',
  '권욱': 'Wook Kwon',
  '김광수': 'Gwang-su Kim',
  '김기혁': 'Ki-hyeok Kim',
  '김남균': 'Nam-gyun Kim',
  '김남명': 'Nam-myeong Kim',
  '김도연': 'Do-yeon Kim',
  '김동호': 'Dong-ho Kim',
  '김병준': 'Byeong-jun Kim',
  '김병훈': 'Byeong-hoon Kim',
  '김선영': 'Seon-yeong Kim',
  '김성태': 'Seong-tae Kim',
  '김세영': 'Se-yeong Kim',
  '김수호': 'Su-ho Kim',
  '김수진': 'Su-jin Kim',
  '김여진': 'Yeo-jin Kim',
  '김연하': 'Yeon-ha Kim',
  '김예솔': 'Ye-sol Kim',
  '김우보': 'U-bo Kim',
  '김유승': 'Yu-seung Kim',
  '김윤수': 'Yoon-su Kim',
  '김은지': 'Eun-ji Kim',
  '김정우': 'Jeong-u Kim',
  '김정현': 'Jung-hyun Kim',
  '김지훈': 'Ji-hoon Kim',
  '김지영': 'Ji-yeong Kim',
  '김태규': 'Tae-gyu Kim',
  '김태영': 'Tae-yeong Kim',
  '김태호': 'Tae-ho Kim',
  '김현우': 'Hyun-woo Kim',
  '김혜란': 'Hye-ran Kim',
  '김흥록': 'Heung-rok Kim',
  '김성호': 'Sung-ho Kim',
  '김영민': 'Young-min Kim',
  '김민수': 'Min-su Kim',

  // ㄴ
  '남윤정': 'Yun-jeong Nam',
  '노우리': 'U-ri Noh',
  '노정동': 'Jung-dong Noh',
  '노해철': 'Hae-cheol Noh',
  '노현섭': 'Hyeon-seop Noh',
  '노현영': 'Hyeon-yeong Noh',

  // ㄷ
  '도예리': 'Ye-ri Do',
  '도혜원': 'Hye-won Do',

  // ㄹ
  '류석': 'Seok Ryu',

  // ㅁ
  '마가연': 'Ga-yeon Ma',
  '문예빈': 'Ye-bin Moon',

  // ㅂ
  '박경훈': 'Gyeong-hun Park',
  '박동휘': 'Dong-hwi Park',
  '박민주': 'Min-ju Park',
  '박민수': 'Min-su Park',
  '박상현': 'Sang-hyun Park',
  '박성호': 'Seong-ho Park',
  '박시은': 'Si-eun Park',
  '박시진': 'Si-jin Park',
  '박우인': 'U-in Park',
  '박윤선': 'Yun-seon Park',
  '박정현': 'Jeong-hyeon Park',
  '박종완': 'Jong-wan Park',
  '박준영': 'Jun-young Park',
  '박준호': 'Jun-ho Park',
  '박지수': 'Ji-su Park',
  '박지훈': 'Ji-hoon Park',
  '박창규': 'Chang-gyu Park',
  '박형윤': 'Hyeong-yun Park',
  '박혜정': 'Hye-jeong Park',
  '박호현': 'Ho-hyeon Park',
  '박효정': 'Hyo-jeong Park',
  '박희윤': 'Hui-yun Park',
  '배상윤': 'Sang-yun Bae',
  '백주연': 'Ju-yeon Baek',

  // ㅅ
  '서민우': 'Min-u Seo',
  '서종갑': 'Jong-gap Seo',
  '서지혜': 'Ji-hye Seo',
  '서정원': 'Jung-won Seo',
  '성채윤': 'Chae-yun Seong',
  '손대선': 'Dae-seon Son',
  '손성락': 'Seong-rak Son',
  '손현진': 'Hyun-jin Son',
  '송종호': 'Jong-ho Song',
  '송주희': 'Ju-hui Song',
  '신서희': 'Seo-hui Shin',
  '신중섭': 'Jung-seop Shin',
  '심기문': 'Gi-mun Shim',

  // ㅇ
  '안경진': 'Gyeong-jin Ahn',
  '안재균': 'Jae-gyun Ahn',
  '양준호': 'Jun-ho Yang',
  '양지혜': 'Ji-hye Yang',
  '양철민': 'Cheol-min Yang',
  '연승': 'Seung Yeon',
  '우영탁': 'Yeong-tak Woo',
  '유민환': 'Min-hwan Yu',
  '유주희': 'Ju-hui Yu',
  '유현욱': 'Hyeon-uk Yu',
  '윤경환': 'Gyeong-hwan Yoon',
  '윤민혁': 'Min-hyeok Yoon',
  '윤지영': 'Ji-yeong Yoon',
  '이건율': 'Geon-yul Lee',
  '이경운': 'Gyeong-un Lee',
  '이경환': 'Gyeong-hwan Lee',
  '이덕연': 'Deok-yeon Lee',
  '이민수': 'Min-su Lee',
  '이수진': 'Su-jin Lee',
  '이승령': 'Seung-ryeong Lee',
  '이승배': 'Seung-bae Lee',
  '이영민': 'Young-min Lee',
  '이영호': 'Yeong-ho Lee',
  '이완기': 'Wan-gi Lee',
  '이용성': 'Yong-seong Lee',
  '이유진': 'Yu-jin Lee',
  '이인애': 'In-ae Lee',
  '이정민': 'Jeong-min Lee',
  '이정훈': 'Jeong-hoon Lee',
  '이종호': 'Jong-ho Lee',
  '이지훈': 'Ji-hoon Lee',
  '이진석': 'Jin-seok Lee',
  '이충희': 'Chung-hee Lee',
  '이태규': 'Tae-gyu Lee',
  '이현우': 'Hyun-woo Lee',
  '이혜진': 'Hye-jin Lee',
  '이준호': 'Jun-ho Lee',
  '임세원': 'Se-won Lim',
  '임종현': 'Jong-hyeon Lim',
  '임혜린': 'Hye-rin Lim',

  // ㅈ
  '장문항': 'Moon-hang Jang',
  '장지승': 'Ji-seung Jang',
  '장형임': 'Hyeong-im Jang',
  '전희윤': 'Hui-yun Jeon',
  '정다은': 'Da-eun Jeong',
  '정문영': 'Moon-yeong Jeong',
  '정민수': 'Min-su Jung',
  '정유민': 'Yu-min Jeong',
  '정재훈': 'Jae-hoon Jung',
  '정혜진': 'Hye-jin Jeong',
  '조수연': 'Su-yeon Cho',
  '조양준': 'Yang-jun Cho',
  '조원진': 'Won-jin Cho',
  '조윤진': 'Yun-jin Cho',
  '조지원': 'Ji-won Cho',
  '조태형': 'Tae-hyeong Cho',
  '조현우': 'Hyun-woo Cho',
  '조민수': 'Min-su Cho',

  // ㅊ
  '채민석': 'Min-seok Chae',
  '천민아': 'Min-a Cheon',
  '최성욱': 'Seong-uk Choi',
  '최수문': 'Su-moon Choi',
  '최수진': 'Su-jin Choi',
  '최영민': 'Young-min Choi',
  '최지훈': 'Ji-hoon Choi',

  // ㅎ
  '한동훈': 'Dong-hoon Han',
  '한민구': 'Min-gu Han',
  '한상현': 'Sang-hyun Han',
  '허진': 'Jin Heo',
  '현수아': 'Su-a Hyeon',
  '황동건': 'Dong-geon Hwang',
  '황민수': 'Min-su Hwang',
};

/**
 * 한글 직책 → 영어 직책 매핑
 */
export const TITLE_MAP: Record<string, string> = {
  '특파원': 'Correspondent',
  '기자': 'Reporter',
  '선임기자': 'Senior Reporter',
  '부장': 'Editor',
  '차장': 'Deputy Editor',
  '팀장': 'Team Leader',
  '전문기자': 'Specialist Reporter',
  '의료전문기자': 'Medical Correspondent',
  '객원기자': 'Contributing Writer',
  '에디터': 'Editor',
  '편집위원': 'Editorial Board Member',
};

/**
 * 지역명 → 영어 지역명 매핑
 */
export const LOCATION_MAP: Record<string, string> = {
  // 해외
  '워싱턴': 'Washington',
  '뉴욕': 'New York',
  '베이징': 'Beijing',
  '도쿄': 'Tokyo',
  '런던': 'London',
  '상하이': 'Shanghai',
  '홍콩': 'Hong Kong',
  '브뤼셀': 'Brussels',
  '파리': 'Paris',
  '실리콘밸리': 'Silicon Valley',
  'LA': 'Los Angeles',

  // 국내
  '수원': 'Suwon',
  '부산': 'Busan',
  '대구': 'Daegu',
  '인천': 'Incheon',
  '광주': 'Gwangju',
  '대전': 'Daejeon',
  '울산': 'Ulsan',
  '세종': 'Sejong',
  '경기': 'Gyeonggi',
  '강원': 'Gangwon',
  '충북': 'Chungbuk',
  '충남': 'Chungnam',
  '전북': 'Jeonbuk',
  '전남': 'Jeonnam',
  '경북': 'Gyeongbuk',
  '경남': 'Gyeongnam',
  '제주': 'Jeju',
};
