/**
 * 한글 기자 이름 → 영어 이름 매핑 테이블
 * 자동 생성: seodaily_byline_data_translated_dedup_byline.xlsx
 * 총 543개 매핑 (2026-01-02 업데이트)
 */
export const REPORTER_NAME_MAP: Record<string, string> = {
  '(Commentary)': '(Commentary)',
  'AI PRISM': 'AI PRISM',
  'Ahn Hyun-duk (Commentary)': 'Ahn Hyun-duk (Commentary)',
  'Ahn Kyung-jin': 'Ahn Kyung-jin',
  'Ahn Kyung-jin (Commentary)': 'Ahn Kyung-jin (Commentary)',
  'Baeksang Forum (Commentary)': 'Baeksang Forum (Commentary)',
  'Chae Min-seok (Commentary)': 'Chae Min-seok (Commentary)',
  'Cho Dong-rye (Poetry)': 'Cho Dong-rye (Poetry)',
  'Cho Tae-hyung': 'Cho Tae-hyung',
  'Cho Yang-jun (Commentary)': 'Cho Yang-jun (Commentary)',
  'Choi Seung-hwan (Commentary)': 'Choi Seung-hwan (Commentary)',
  'Choi Soo-moon (Commentary)': 'Choi Soo-moon (Commentary)',
  'Decenter': 'Decenter',
  'Editorial Board (Commentary)': 'Editorial Board (Commentary)',
  'Editorial Board (Opinion)': 'Editorial Board (Opinion)',
  'Fareed Zakaria (Commentary)': 'Fareed Zakaria (Commentary)',
  'George Will (Commentary)': 'George Will (Commentary)',
  'Guest Contributor (Opinion)': 'Guest Contributor (Opinion)',
  'Han Dong-hoon': 'Han Dong-hoon',
  'Hong Ki-won': 'Hong Ki-won',
  'Jo Yang-jun (Commentary)': 'Jo Yang-jun (Commentary)',
  'Kim (Commentary)': 'Kim (Commentary)',
  'Kim Chang-young': 'Kim Chang-young',
  'Kim Chang-young (Commentary)': 'Kim Chang-young (Commentary)',
  'Kim Hye-ran': 'Kim Hye-ran',
  'Kim Hyun-ki (Commentary)': 'Kim Hyun-ki (Commentary)',
  'Kim Ji-young and Lee Jin-seok': 'Kim Ji-young and Lee Jin-seok',
  'Kim Ki-hyuk': 'Kim Ki-hyuk',
  'Kim Kwang-duk (Commentary)': 'Kim Kwang-duk (Commentary)',
  'Kim Kwang-soo (Commentary)': 'Kim Kwang-soo (Commentary)',
  'Kim Min-seok': 'Kim Min-seok',
  'Kim Seung-hyun (Commentary)': 'Kim Seung-hyun (Commentary)',
  'Kim So-young (Commentary)': 'Kim So-young (Commentary)',
  'Kim Su-ho': 'Kim Su-ho',
  'Kim Sung-tae (Commentary)': 'Kim Sung-tae (Commentary)',
  'Kim Tae-young': 'Kim Tae-young',
  'Kim Yoon-soo': 'Kim Yoon-soo',
  'Kim Young-wook (Opinion)': 'Kim Young-wook (Opinion)',
  'Ko Hak-soo (Commentary)': 'Ko Hak-soo (Commentary)',
  'Kook Kyung-bok (Commentary)': 'Kook Kyung-bok (Commentary)',
  'Lee Chung-hee (Commentary)': 'Lee Chung-hee (Commentary)',
  'Lee Dong-hwan': 'Lee Dong-hwan',
  'Lee Hyun-ho': 'Lee Hyun-ho',
  'Lee Hyun-ho (Commentary)': 'Lee Hyun-ho (Commentary)',
  'Lee Kun-yul': 'Lee Kun-yul',
  'Lee Kyung-hwan': 'Lee Kyung-hwan',
  'Lee Sang-hoon': 'Lee Sang-hoon',
  'Lee Tae-kyu': 'Lee Tae-kyu',
  'Lee Tae-kyu (Commentary)': 'Lee Tae-kyu (Commentary)',
  'Lim Byung-sik (Commentary)': 'Lim Byung-sik (Commentary)',
  'Megan McArdle (Commentary)': 'Megan McArdle (Commentary)',
  'Oh In-tae (Poetry)': 'Oh In-tae (Poetry)',
  'Oh Seung-hyun': 'Oh Seung-hyun',
  'Oh Tae-sik (Commentary)': 'Oh Tae-sik (Commentary)',
  'Park Sun-tae (Commentary)': 'Park Sun-tae (Commentary)',
  'Pick Economy Team': 'Pick Economy Team',
  'Reporter (Commentary)': 'Reporter (Commentary)',
  'Sedaily Editorial (Commentary)': 'Sedaily Editorial (Commentary)',
  'Seo Jong-gap': 'Seo Jong-gap',
  'Seo Jong-gap (Commentary)': 'Seo Jong-gap (Commentary)',
  'Seoul Economic Daily': 'Seoul Economic Daily',
  'Seoul Economic Daily (Commentary)': 'Seoul Economic Daily (Commentary)',
  'Seoul Economic Daily (Opinion)': 'Seoul Economic Daily (Opinion)',
  'Seoul Economic Daily (Review)': 'Seoul Economic Daily (Review)',
  'Seoul Economic Daily AI PRISM Team': 'Seoul Economic Daily AI PRISM Team',
  'Seoul Economic Daily AI Prism Team': 'Seoul Economic Daily AI Prism Team',
  'Seoul Economic Daily AI Team': 'Seoul Economic Daily AI Team',
  'Seoul Economic Daily Editorial Board (Opinion)': 'Seoul Economic Daily Editorial Board (Opinion)',
  'Seoul Economic Daily Lifestyle Desk': 'Seoul Economic Daily Lifestyle Desk',
  'Seoul Economy Daily': 'Seoul Economy Daily',
  'Seoul Economy Staff': 'Seoul Economy Staff',
  'Seoul Kyungje AI PRISM Team': 'Seoul Kyungje AI PRISM Team',
  'Seoul Kyungje Daily': 'Seoul Kyungje Daily',
  'Seoul Kyungje Staff': 'Seoul Kyungje Staff',
  'Song Jong-ho (Commentary)': 'Song Jong-ho (Commentary)',
  'Song Joo-hee': 'Song Joo-hee',
  'Song Joo-hee (Commentary)': 'Song Joo-hee (Commentary)',
  'Song Ju-hee': 'Song Ju-hee',
  'Staff Reporter': 'Staff Reporter',
  'Staff Reporter (Commentary)': 'Staff Reporter (Commentary)',
  'Staff Writer (Commentary)': 'Staff Writer (Commentary)',
  'Staff Writer (Opinion)': 'Staff Writer (Opinion)',
  'Sun Seung-hye (Commentary)': 'Sun Seung-hye (Commentary)',
  'Sung Hyung-joo': 'Sung Hyung-joo',
  'The Seoul Economic Daily (Editorial)': 'The Seoul Economic Daily (Editorial)',
  'The Seoul Economic Daily (Opinion)': 'The Seoul Economic Daily (Opinion)',
  'The Seoul Economic Daily Editorial Board (Opinion)': 'The Seoul Economic Daily Editorial Board (Opinion)',
  'Unknown (Commentary)': 'Unknown (Commentary)',
  'Yang Jong-gon (Commentary)': 'Yang Jong-gon (Commentary)',
  'Yoon Seung-yeon (Commentary)': 'Yoon Seung-yeon (Commentary)',
  '가평=이경환 기자': 'Gapyeong - Lee Gyeong-Hwan',
  '강도림 기자': 'Kang Do-Rim',
  '강도림 기자,도혜원 기자': 'Kang Do-Rim, Do Hye-Won',
  '강도림 기자,이승령 기자': 'Kang Do-Rim, Lee Seung-Ryeong',
  '강동헌 기자': 'Kang Dong-Heon',
  '강동효 기자': 'Kang Dong-Hyo',
  '강동효 기자,박창규 기자': 'Kang Dong-Hyo, Park Chang-Gyu',
  '강동효 기자,박형윤 기자': 'Kang Dong-Hyo, Park Hyeong-Yun',
  '강신우 기자': 'Kang Sin-U',
  '강진=박지훈 기자': 'Gangjin - Park Ji-Hun',
  '거제=박종완 기자': 'Geoje - Park Jong-Wan',
  '경산=손성락 기자': 'Gyeongsan - Son Seong-Rak',
  '고광본 논설위원·선임기자': 'Ko Gwang-Bon (Editorial Writer), Seon Im',
  '고광본 선임기자': 'Ko Gwang-Bon (Senior Reporter)',
  '고민성 NH투자증권 연구원': 'Ko Min-Seong NHTu Ja-Jeung-Gwon Yeon Gu-Won',
  '고성=박종완 기자': 'Goseong - Park Jong-Wan',
  '고양=김성태 기자': 'Goyang - Kim Seong-Tae',
  '고양=이경환 기자': 'Goyang - Lee Gyeong-Hwan',
  '공준호 기자': 'Gong Jun-Ho',
  '공준호 기자,김우보 기자': 'Gong Jun-Ho, Kim U-Bo',
  '광주=박지훈 기자': 'Gwangju - Park Ji-Hun',
  '광주=손대선 기자': 'Gwangju - Son Dae-Seon',
  '구경우 기자': 'Koo Gyeong-U',
  '구경우 기자,허진 기자': 'Koo Gyeong-U, Heo Jin',
  '구리=이경환 기자': 'Guri - Lee Gyeong-Hwan',
  '구리·동두천=이경환 기자': 'Koo Ri, Dongducheon - Lee Gyeong-Hwan',
  '구미=손성락 기자': 'Gumi - Son Seong-Rak',
  '구미=심기문 기자': 'Gumi - Shim Gi-Mun',
  '군포=손대선 기자': 'Gunpo - Son Dae-Seon',
  '권욱 기자': 'Kwon Uk',
  '글·사(광주)=박우인 기자': 'Geul, Sa(gwangju) - Park U-In',
  '글·사진(광주)=박우인 기자': 'Geul, Sajin(gwangju) - Park U-In',
  '글·사진(바르샤바)=심우일 기자': 'Geul, Sajin(bareusyaba) - Shim U-Il',
  '글·사진(방콕)=양지혜 기자': 'Geul, Sajin(bangkok) - Yang Ji-Hye',
  '글·사진(워싱턴)=이태규 특파원,서지혜 기자': 'Geul, Sajin(wosingteon) - Lee Tae-Gyu (Correspondent), Seo Ji-Hye',
  '글·사진(청주)=김태호 기자': 'Geul, Sajin(cheongju) - Kim Tae-Ho',
  '글·사진=고광본 선임기자': 'Geul, Sajin - Ko Gwang-Bon (Senior Reporter)',
  '글·사진=노현영 기자': 'Geul, Sajin - Roh Hyeon-Yeong',
  '글·사진=양준호 기자': 'Geul, Sajin - Yang Jun-Ho',
  '글·사진=이종호 기자': 'Geul, Sajin - Lee Jong-Ho',
  '김경미 기자': 'Kim Gyeong-Mi',
  '김경훈 기자': 'Kim Gyeong-Hun',
  '김기혁 기자': 'Kim Gi-Hyeok',
  '김기혁·김윤수 기자': 'Kim Gi-Hyeok, Kim Yun-Su',
  '김남균 기자': 'Kim Nam-Gyun',
  '김남균 기자,윤지영 기자': 'Kim Nam-Gyun, Yoon Ji-Yeong',
  '김남명 기자': 'Kim Nam-Myeong',
  '김도연 기자': 'Kim Do-Yeon',
  '김동호 기자': 'Kim Dong-Ho',
  '김민 스테이트 스트리트 은행 한국 대표': 'Kim Min Seu Te-I-Teu Seu Teu-Ri-Teu Eun Haeng Han Guk Dae Pyo',
  '김병준 기자': 'Kim Byeong-Jun',
  '김병준 기자,김혜란 기자': 'Kim Byeong-Jun, Kim Hye-Ran',
  '김병준 기자,박시은 기자': 'Kim Byeong-Jun, Park Si-Eun',
  '김병준 기자,박신원 기자': 'Kim Byeong-Jun, Park Sin-Won',
  '김병준 기자,이충희 기자': 'Kim Byeong-Jun, Lee Chung-Hui',
  '김병훈 기자': 'Kim Byeong-Hun',
  '김병훈 기자,김유승 기자': 'Kim Byeong-Hun, Kim Yu-Seung',
  '김병훈 기자,도혜원 기자': 'Kim Byeong-Hun, Do Hye-Won',
  '김병훈 기자,마가연 기자': 'Kim Byeong-Hun, Ma Ga-Yeon',
  '김병훈 기자,이승령 기자': 'Kim Byeong-Hun, Lee Seung-Ryeong',
  '김선영 기자': 'Kim Seon-Yeong',
  '김선영 기자,채민석 기자': 'Kim Seon-Yeong, Chae Min-Seok',
  '김성태 기자': 'Kim Seong-Tae',
  '김성태 기자,김흥록 기자': 'Kim Seong-Tae, Kim Heung-Rok',
  '김성태 기자,양지혜 기자': 'Kim Seong-Tae, Yang Ji-Hye',
  '김성태 기자,이승배 기자': 'Kim Seong-Tae, Lee Seung-Bae',
  '김세영 기자': 'Kim Se-Yeong',
  '김세환 KB증권 리서치본부 수석연구위원': 'Kim Se-Hwan KBJeung Gwon Riseochibonbu Suseokyeonguwiwon',
  '김수호 기자': 'Kim Su-Ho',
  '김여진 기자': 'Kim Yeo-Jin',
  '김연하 기자': 'Kim Yeon-Ha',
  '김영필 기자': 'Kim Yeong-Pil',
  '김예솔 기자': 'Kim Ye-Sol',
  '김예솔 기자,김태호 기자': 'Kim Ye-Sol, Kim Tae-Ho',
  '김우보 기자': 'Kim U-Bo',
  '김우보 기자,김남균 기자': 'Kim U-Bo, Kim Nam-Gyun',
  '김우보 기자,서종갑 기자': 'Kim U-Bo, Seo Jong-Gap',
  '김우보 기자,신중섭 기자': 'Kim U-Bo, Shin Jung-Seop',
  '김우보 기자,이승배 기자': 'Kim U-Bo, Lee Seung-Bae',
  '김유승 기자': 'Kim Yu-Seung',
  '김유승 기자,도혜원 기자': 'Kim Yu-Seung, Do Hye-Won',
  '김유승 기자,마가연 기자': 'Kim Yu-Seung, Ma Ga-Yeon',
  '김윤수 기자': 'Kim Yun-Su',
  '김윤수 기자,김기혁 기자': 'Kim Yun-Su, Kim Gi-Hyeok',
  '김정곤 논설위원': 'Kim Jeong-Gon (Editorial Writer)',
  '김정우 기자': 'Kim Jeong-U',
  '김정우 기자,도예리 기자': 'Kim Jeong-U, Do Ye-Ri',
  '김정욱 기자': 'Kim Jeong-Uk',
  '김지영 기자': 'Kim Ji-Yeong',
  '김지영 기자,김연하 기자': 'Kim Ji-Yeong, Kim Yeon-Ha',
  '김지영 기자,송종호 기자': 'Kim Ji-Yeong, Song Jong-Ho',
  '김지영 기자,이경운 기자': 'Kim Ji-Yeong, Lee Gyeong-Un',
  '김지영 기자,이용성 기자': 'Kim Ji-Yeong, Lee Yong-Seong',
  '김태영 기자': 'Kim Tae-Yeong',
  '김태호 기자': 'Kim Tae-Ho',
  '김태호 기자,류석 기자': 'Kim Tae-Ho, Ryu Seok',
  '김포=이경환 기자': 'Gimpo - Lee Gyeong-Hwan',
  '김해=박종완 기자': 'Gimhae - Park Jong-Wan',
  '김현상 기자': 'Kim Hyeon-Sang',
  '김현상 기자,이승배 기자': 'Kim Hyeon-Sang, Lee Seung-Bae',
  '김현수 논설위원': 'Kim Hyeon-Su (Editorial Writer)',
  '김혜란 기자': 'Kim Hye-Ran',
  '김혜란 기자,한동훈 기자': 'Kim Hye-Ran, Han Dong-Hun',
  '김흥록 기자': 'Kim Heung-Rok',
  '김흥록 기자,김성태 기자': 'Kim Heung-Rok, Kim Seong-Tae',
  '김흥일 케이유니콘인베스트먼트 대표': 'Kim Heung-Il Keiyunikoninbeseuteumeonteu Dae Pyo',
  '나주=박지훈 기자': 'Naju - Park Ji-Hun',
  '남양주=이경환 기자': 'Namyangju - Lee Gyeong-Hwan',
  '남윤정 기자': 'Nam Yun-Jeong',
  '남해=박종완 기자': 'Namhae - Park Jong-Wan',
  '노우리 기자': 'Roh U-Ri',
  '노해철 기자': 'Roh Hae-Cheol',
  '노해철 기자,김우보 기자': 'Roh Hae-Cheol, Kim U-Bo',
  '노해철 기자,이건율 기자': 'Roh Hae-Cheol, Lee Geon-Yul',
  '노현섭 기자': 'Roh Hyeon-Seop',
  '노현영 기자': 'Roh Hyeon-Yeong',
  '노희영 기자': 'Roh Hui-Yeong',
  '논산=박희윤 기자': 'Nonsan - Park Hui-Yun',
  '논설위원실': 'Nonseolwiwonsil',
  '뉴욕=윤경환 특파원': 'New York - Yoon Gyeong-Hwan (Correspondent)',
  '닝보=김광수 특파원': 'Ningbo - Kim Gwang-Su (Correspondent)',
  '대구=손성락 기자': 'Daegu - Son Seong-Rak',
  '대구=이정민 기자': 'Daegu - Lee Jeong-Min',
  '대전=박희윤 기자': 'Daejeon - Park Hui-Yun',
  '대전·청주=박희윤 기자': 'Dae Jeon, Cheongju - Park Hui-Yun',
  '도예리 기자': 'Do Ye-Ri',
  '도예리 기자,박민주 기자': 'Do Ye-Ri, Park Min-Ju',
  '도쿄=신중섭 기자': 'Tokyo - Shin Jung-Seop',
  '도혜원 기자': 'Do Hye-Won',
  '도혜원 기자,김병훈 기자': 'Do Hye-Won, Kim Byeong-Hun',
  '도혜원 기자,박창규 기자': 'Do Hye-Won, Park Chang-Gyu',
  '동두천=이경환 기자': 'Dongducheon - Lee Gyeong-Hwan',
  '류석 기자': 'Ryu Seok',
  '류석 기자,사진=조태형기자 기자': 'Ryu Seok, Sajin - Jotaehyeonggija',
  '마가연 기자': 'Ma Ga-Yeon',
  '마가연 기자,김병훈 기자': 'Ma Ga-Yeon, Kim Byeong-Hun',
  '마가연 기자,도혜원 기자': 'Ma Ga-Yeon, Do Hye-Won',
  '메리보로=심기문 기자': 'Meriboro - Shim Gi-Mun',
  '목포·순천=박지훈 기자': 'Mok Po, Suncheon - Park Ji-Hun',
  '무안=박지훈 기자': 'Muan - Park Ji-Hun',
  '문성진 논설실장': 'Moon Seong-Jin Non Seol-Sil-Jang',
  '문승환 한국투자증권 연구원': 'Moon Seung-Hwan Hanguktujajeunggwon Yeon Gu-Won',
  '문예빈 기자': 'Moon Ye-Bin',
  '문화부': 'Moon Hwa-Bu',
  '민병권 논설위원': 'Min Byeong-Gwon (Editorial Writer)',
  '민주영 신영증권 연금사업부 이사': 'Min Ju-Yeong Shin Yeong-Jeung-Gwon Yeongeumsaeopbu Lee Sa',
  '밀양=박종완 기자': 'Milyang - Park Jong-Wan',
  '박경훈 기자': 'Park Gyeong-Hun',
  '박동휘 기자': 'Park Dong-Hwi',
  '박민주 기자': 'Park Min-Ju',
  '박민주 기자,강도림 기자': 'Park Min-Ju, Kang Do-Rim',
  '박민주 기자,김정우 기자': 'Park Min-Ju, Kim Jeong-U',
  '박민주 기자,도예리 기자': 'Park Min-Ju, Do Ye-Ri',
  '박민주 기자,황동건 기자': 'Park Min-Ju, Hwang Dong-Geon',
  '박성호 기자': 'Park Seong-Ho',
  '박성호 기자,김우보 기자': 'Park Seong-Ho, Kim U-Bo',
  '박성호 기자,김유승 기자': 'Park Seong-Ho, Kim Yu-Seung',
  '박성호 기자,김혜란 기자': 'Park Seong-Ho, Kim Hye-Ran',
  '박성호 기자,박시은 기자': 'Park Seong-Ho, Park Si-Eun',
  '박성호 기자,이충희 기자': 'Park Seong-Ho, Lee Chung-Hui',
  '박성호 기자,정혜진 기자': 'Park Seong-Ho, Jung Hye-Jin',
  '박시은 기자': 'Park Si-Eun',
  '박시은 기자,김병준 기자': 'Park Si-Eun, Kim Byeong-Jun',
  '박시은 기자,이충희 기자': 'Park Si-Eun, Lee Chung-Hui',
  '박시진 기자': 'Park Si-Jin',
  '박신원 기자': 'Park Sin-Won',
  '박신원 기자,배상윤 기자': 'Park Sin-Won, Bae Sang-Yun',
  '박우인 기자': 'Park U-In',
  '박윤선 기자': 'Park Yun-Seon',
  '박정현 기자': 'Park Jeong-Hyeon',
  '박정현 기자,변수연 기자': 'Park Jeong-Hyeon, Byun Su-Yeon',
  '박준호 기자': 'Park Jun-Ho',
  '박지수 기자': 'Park Ji-Su',
  '박지수 기자,김현상 기자': 'Park Ji-Su, Kim Hyeon-Sang',
  '박창규 기자': 'Park Chang-Gyu',
  '박창규 기자,임종현 기자': 'Park Chang-Gyu, Lim Jong-Hyeon',
  '박태준 기자': 'Park Tae-Jun',
  '박형윤 기자': 'Park Hyeong-Yun',
  '박형윤 기자,쿠알라룸푸르=박창규 기자,진동영 기자': 'Park Hyeong-Yun, Kualrarumpureu - Park Chang-Gyu, Jin Dong-Yeong',
  '박혜정 기자': 'Park Hye-Jeong',
  '박호현 기자': 'Park Ho-Hyeon',
  '박호현 기자,성채윤 기자': 'Park Ho-Hyeon, Sung Chae-Yun',
  '박호현 기자,양철민 기자': 'Park Ho-Hyeon, Yang Cheol-Min',
  '박호현 기자,진동영 기자': 'Park Ho-Hyeon, Jin Dong-Yeong',
  '박효정 기자': 'Park Hyo-Jeong',
  '박희운 한국투자신탁운용 솔루션본부장': 'Park Hui-Un Hanguktujasintakunyong Solrusyeonbonbujang',
  '박희윤 기자': 'Park Hui-Yun',
  '방콕·치앙마이=이경운 기자': 'Bang Kok, Chiangmai - Lee Gyeong-Un',
  '배상윤 기자': 'Bae Sang-Yun',
  '백주연 기자': 'Baek Ju-Yeon',
  '백주연 기자,강동효 기자': 'Baek Ju-Yeon, Kang Dong-Hyo',
  '백주연 기자,천민아 기자': 'Baek Ju-Yeon, Chun Min-A',
  '베이징=김광수 특파원': 'Beijing - Kim Gwang-Su (Correspondent)',
  '변수연 기자': 'Byun Su-Yeon',
  '변수연 기자,워싱턴=이태규 특파원': 'Byun Su-Yeon, Washington - Lee Tae-Gyu (Correspondent)',
  '보령=박희윤 기자': 'Boryeong - Park Hui-Yun',
  '보성=박지훈 기자': 'Boseong - Park Ji-Hun',
  '부산=양준호 기자': 'Busan - Yang Jun-Ho',
  '부산=장지승 기자': 'Busan - Jang Ji-Seung',
  '부산=조원진 기자': 'Busan - Cho Won-Jin',
  '부천=손대선 기자': 'Bucheon - Son Dae-Seon',
  '브랜던 머피 BNY 인베스트먼트?북미 채권 헤드': 'Beu Raen-Deon Meo Pi BNY Inbeseuteumeonteu?Buk Mi Chae Gwon He Deu',
  '사천=박종완 기자': 'Sacheon - Park Jong-Wan',
  '서경IN': 'Seo GyeongIN',
  '서민우 기자': 'Seo Min-U',
  '서민우 기자,박신원 기자': 'Seo Min-U, Park Sin-Won',
  '서민우 기자,유현욱 기자': 'Seo Min-U, Yu Hyeon-Uk',
  '서산=박희윤 기자': 'Seosan - Park Hui-Yun',
  '서울=손대선 기자': 'Seoul - Son Dae-Seon',
  '서울경제 오토랩 김학수 기자': 'Seo Ul-Gyeong-Je Oh To-Raep Kim Hak-Su',
  '서정명 기자': 'Seo Jeong-Myeong',
  '서정명 논설위원': 'Seo Jeong-Myeong (Editorial Writer)',
  '서종갑 기자': 'Seo Jong-Gap',
  '서지혜 기자': 'Seo Ji-Hye',
  '성남=김기혁 기자': 'Seongnam - Kim Gi-Hyeok',
  '성남=김태호 기자': 'Seongnam - Kim Tae-Ho',
  '성남=손대선 기자': 'Seongnam - Son Dae-Seon',
  '성채윤 기자': 'Sung Chae-Yun',
  '성채윤 기자,박호현 기자': 'Sung Chae-Yun, Park Ho-Hyeon',
  '성형주 기자': 'Sung Hyeong-Ju',
  '세종=박희윤 기자': 'Sejong - Park Hui-Yun',
  '손철 기자': 'Son Cheol',
  '송종호 기자': 'Song Jong-Ho',
  '송종호 기자,박준호 기자': 'Song Jong-Ho, Park Jun-Ho',
  '송종호 기자,세종=전희윤 기자': 'Song Jong-Ho, Sejong - Jeon Hui-Yun',
  '송종호 기자,전희윤 기자': 'Song Jong-Ho, Jeon Hui-Yun',
  '송주희 기자': 'Song Ju-Hui',
  '송주희 기자,베이징=김광수 특파원': 'Song Ju-Hui, Beijing - Kim Gwang-Su (Correspondent)',
  '송주희 기자,워싱턴=이태규 특파원': 'Song Ju-Hui, Washington - Lee Tae-Gyu (Correspondent)',
  '수원=손대선 기자': 'Suwon - Son Dae-Seon',
  '순천=박지훈 기자': 'Suncheon - Park Ji-Hun',
  '시드니=심기문 기자': 'Sydney - Shim Gi-Mun',
  '시드니·메리보로=심기문 기자': 'Si Deu-Ni, Meriboro - Shim Gi-Mun',
  '시흥=손대선 기자': 'Siheung - Son Dae-Seon',
  '신경립 논설위원': 'Shin Gyeong-Rip (Editorial Writer)',
  '신서희 기자': 'Shin Seo-Hui',
  '신안=박지훈 기자': 'Sinan - Park Ji-Hun',
  '신중섭 기자': 'Shin Jung-Seop',
  '신중섭 기자,김우보 기자': 'Shin Jung-Seop, Kim U-Bo',
  '신중섭 기자,김정우 기자': 'Shin Jung-Seop, Kim Jeong-U',
  '신중섭 기자,이승배 기자': 'Shin Jung-Seop, Lee Seung-Bae',
  '실리콘밸리=김창영 특파원': 'Silicon Valley - Kim Chang-Yeong (Correspondent)',
  '실리콘밸리=윤민혁 특파원': 'Silicon Valley - Yoon Min-Hyeok (Correspondent)',
  '심기문 기자': 'Shim Gi-Mun',
  '심우일 기자': 'Shim U-Il',
  '심우일 기자,뉴욕=윤경환 특파원': 'Shim U-Il, New York - Yoon Gyeong-Hwan (Correspondent)',
  '심우일 기자,서종갑 기자,김우보 기자': 'Shim U-Il, Seo Jong-Gap, Kim U-Bo',
  '심우일 기자,이승배 기자': 'Shim U-Il, Lee Seung-Bae',
  '안경진 의료전문기자': 'Ahn Gyeong-Jin (Medical Reporter)',
  '안동=손성락 기자': 'Andong - Son Seong-Rak',
  '안상희 김앤장 법률사무소 센터장': 'Ahn Sang-Hui Kim Aen-Jang Beopryulsamuso Sen Teo-Jang',
  '안성=손대선 기자': 'Anseong - Son Dae-Seon',
  '안양=손대선 기자': 'Anyang - Son Dae-Seon',
  '안현덕 법조전문기자': 'Ahn Hyeon-Deok Beop Jo-Jeon-Mun',
  '양산=박종완 기자': 'Yangsan - Park Jong-Wan',
  '양종곤 고용노동전문기자': 'Yang Jong-Gon Goyongnodongjeonmun',
  '양주=이경환 기자': 'Yangju - Lee Gyeong-Hwan',
  '양준호 기자': 'Yang Jun-Ho',
  '양준호 기자  사진=성형주 기자': 'Yangjunho gija sajin - Sung Hyeong-Ju',
  '양지혜 기자': 'Yang Ji-Hye',
  '양철민 기자': 'Yang Cheol-Min',
  '에마드 사미 슈로더 캐피탈 포트폴리오 및 솔루션 디렉터': 'E Ma-Deu Sa Mi Syu Ro-Deo Kae Pi-Tal Poteupolrio, Sol Ru-Syeon Di Rek-Teo',
  '여론독자부': 'Yeorondokjabu',
  '여론독자부 기자': 'Yeorondokjabu',
  '여주=손대선 기자': 'Yeoju - Son Dae-Seon',
  '연승 기자': 'Yeon Seung',
  '연천=박신원 기자': 'Yeoncheon - Park Sin-Won',
  '연천=이경환 기자': 'Yeoncheon - Lee Gyeong-Hwan',
  '영암=박지훈 기자': 'Yeongam - Park Ji-Hun',
  '영주=손성락 기자': 'Yeongju - Son Seong-Rak',
  '오산=손대선 기자': 'Osan - Son Dae-Seon',
  '오승현 기자': 'Oh Seung-Hyeon',
  '오태식 기자': 'Oh Tae-Sik',
  '용인=김예솔 기자': 'Yongin - Kim Ye-Sol',
  '용인=손대선 기자': 'Yongin - Son Dae-Seon',
  '우승호 기자,박세은 인턴기자': 'Woo Seung-Ho, Park Se-Eun (Intern Reporter)',
  '우승호 기자,성예현 기자': 'Woo Seung-Ho, Sung Ye-Hyeon',
  '우승호 기자,성예현 인턴기자': 'Woo Seung-Ho, Sung Ye-Hyeon (Intern Reporter)',
  '우영탁 기자': 'Woo Yeong-Tak',
  '울산=장지승 기자': 'Ulsan - Jang Ji-Seung',
  '워싱턴=이태규 특파원': 'Washington - Lee Tae-Gyu (Correspondent)',
  '워싱턴=이태규 특파원,베이징=김광수 특파원': 'Washington - Lee Tae-Gyu (Correspondent), Beijing - Kim Gwang-Su (Correspondent)',
  '워싱턴=이태규 특파원,이현호 기자': 'Washington - Lee Tae-Gyu (Correspondent), Lee Hyeon-Ho',
  '워싱턴=이태규 특파원,정다은 기자': 'Washington - Lee Tae-Gyu (Correspondent), Jung Da-Eun',
  '유민환 기자': 'Yu Min-Hwan',
  '유민환 기자,노해철 기자': 'Yu Min-Hwan, Roh Hae-Cheol',
  '유주희 기자': 'Yu Ju-Hui',
  '유주희 기자,박성호 기자': 'Yu Ju-Hui, Park Seong-Ho',
  '유주희 기자,송종호 기자': 'Yu Ju-Hui, Song Jong-Ho',
  '유주희 기자,워싱턴=이태규 특파원': 'Yu Ju-Hui, Washington - Lee Tae-Gyu (Correspondent)',
  '유주희 기자,정상훈 기자': 'Yu Ju-Hui, Jung Sang-Hun',
  '유현욱 기자': 'Yu Hyeon-Uk',
  '유현욱 기자,김우보 기자': 'Yu Hyeon-Uk, Kim U-Bo',
  '유현욱 기자,김혜란 기자,한동훈 기자': 'Yu Hyeon-Uk, Kim Hye-Ran, Han Dong-Hun',
  '유현욱 기자,박신원 기자': 'Yu Hyeon-Uk, Park Sin-Won',
  '유현욱 기자,서민우 기자': 'Yu Hyeon-Uk, Seo Min-U',
  '윤민혁 기자': 'Yoon Min-Hyeok',
  '윤지영 기자': 'Yoon Ji-Yeong',
  '윤지영 기자,이정훈 기자': 'Yoon Ji-Yeong, Lee Jeong-Hun',
  '윤지영 기자,이충희 기자': 'Yoon Ji-Yeong, Lee Chung-Hui',
  '윤지영 기자,정유민 기자': 'Yoon Ji-Yeong, Jung Yu-Min',
  '윤지영 기자,조지원 기자': 'Yoon Ji-Yeong, Cho Ji-Won',
  '윤홍우 기자': 'Yoon Hong-U',
  '의령=박종완 기자': 'Uiryeong - Park Jong-Wan',
  '의왕=손대선 기자': 'Uiwang - Son Dae-Seon',
  '의정부=이경환 기자': 'Uijeongbu - Lee Gyeong-Hwan',
  '이건율 기자': 'Lee Geon-Yul',
  '이건율 기자,노해철 기자': 'Lee Geon-Yul, Roh Hae-Cheol',
  '이건율 기자,주재현 기자': 'Lee Geon-Yul, Joo Jae-Hyeon',
  '이경운 기자': 'Lee Gyeong-Un',
  '이금숙 기자': 'Lee Geum-Suk',
  '이덕연 기자': 'Lee Deok-Yeon',
  '이상훈 기자': 'Lee Sang-Hun',
  '이승령 기자': 'Lee Seung-Ryeong',
  '이승령 기자,김병훈 기자': 'Lee Seung-Ryeong, Kim Byeong-Hun',
  '이승령 기자,마가연 기자': 'Lee Seung-Ryeong, Ma Ga-Yeon',
  '이승배 기자': 'Lee Seung-Bae',
  '이승배 기자,박지수 기자': 'Lee Seung-Bae, Park Ji-Su',
  '이승배 기자,심우일 기자': 'Lee Seung-Bae, Shim U-Il',
  '이승배 기자,윤지영 기자': 'Lee Seung-Bae, Yoon Ji-Yeong',
  '이영호 기자': 'Lee Yeong-Ho',
  '이완기 기자': 'Lee Wan-Gi',
  '이용성 기자': 'Lee Yong-Seong',
  '이용성 기자,김지영 기자': 'Lee Yong-Seong, Kim Ji-Yeong',
  '이용성 기자,양지혜 기자': 'Lee Yong-Seong, Yang Ji-Hye',
  '이용성 기자,이완기 기자': 'Lee Yong-Seong, Lee Wan-Gi',
  '이유진 기자': 'Lee Yu-Jin',
  '이유진 기자,이진석 기자': 'Lee Yu-Jin, Lee Jin-Seok',
  '이유진 기자,채민석 기자': 'Lee Yu-Jin, Chae Min-Seok',
  '이인애 기자': 'Lee In-Ae',
  '이정민 기자': 'Lee Jeong-Min',
  '이정훈 기자': 'Lee Jeong-Hun',
  '이종호 기자': 'Lee Jong-Ho',
  '이종호 기자,정문영 기자': 'Lee Jong-Ho, Jung Mun-Yeong',
  '이진석 기자': 'Lee Jin-Seok',
  '이진석 기자,김병훈 기자': 'Lee Jin-Seok, Kim Byeong-Hun',
  '이진석 기자,김유승 기자': 'Lee Jin-Seok, Kim Yu-Seung',
  '이진석 기자,도혜원 기자': 'Lee Jin-Seok, Do Hye-Won',
  '이진석 기자,마가연 기자': 'Lee Jin-Seok, Ma Ga-Yeon',
  '이진석 기자,사진=권욱 기자': 'Lee Jin-Seok, Sajin - Kwon Uk',
  '이진석 기자,이승령 기자': 'Lee Jin-Seok, Lee Seung-Ryeong',
  '이찬영 유진투자증권 연구원': 'Lee Chan-Yeong Yujintujajeunggwon Yeon Gu-Won',
  '이충희 기자': 'Lee Chung-Hui',
  '이충희 기자,박시은 기자': 'Lee Chung-Hui, Park Si-Eun',
  '이충희 기자,이덕연 기자': 'Lee Chung-Hui, Lee Deok-Yeon',
  '이충희 기자,임세원 기자': 'Lee Chung-Hui, Lim Se-Won',
  '이현호 기자': 'Lee Hyeon-Ho',
  '이현호 기자,송종호 기자': 'Lee Hyeon-Ho, Song Jong-Ho',
  '이혜진 선임기자': 'Lee Hye-Jin (Senior Reporter)',
  '이혜진 선임기자,김경미 기자': 'Lee Hye-Jin (Senior Reporter), Kim Gyeong-Mi',
  '인천=안재균 기자': 'Incheon - Ahn Jae-Gyun',
  '임세원 기자': 'Lim Se-Won',
  '임세원 기자,김병준 기자': 'Lim Se-Won, Kim Byeong-Jun',
  '임세원 기자,이충희 기자': 'Lim Se-Won, Lee Chung-Hui',
  '임종현 기자': 'Lim Jong-Hyeon',
  '임종현 기자,도혜원 기자': 'Lim Jong-Hyeon, Do Hye-Won',
  '임종현 기자,채민석 기자': 'Lim Jong-Hyeon, Chae Min-Seok',
  '임혜린 기자': 'Lim Hye-Rin',
  '장문항 기자': 'Jang Mun-Hang',
  '장형임 기자': 'Jang Hyeong-Im',
  '전희윤 기자': 'Jeon Hui-Yun',
  '전희윤 기자,도혜원 기자': 'Jeon Hui-Yun, Do Hye-Won',
  '전희윤 기자,박신원 기자': 'Jeon Hui-Yun, Park Sin-Won',
  '전희윤 기자,송종호 기자': 'Jeon Hui-Yun, Song Jong-Ho',
  '전희윤 기자,유민환 기자': 'Jeon Hui-Yun, Yu Min-Hwan',
  '전희윤 기자,유주희 기자': 'Jeon Hui-Yun, Yu Ju-Hui',
  '전희윤 기자,정상훈 기자': 'Jeon Hui-Yun, Jung Sang-Hun',
  '정다은 기자': 'Jung Da-Eun',
  '정다은 기자,주재현 기자': 'Jung Da-Eun, Joo Jae-Hyeon',
  '정문영 기자': 'Jung Mun-Yeong',
  '정문영 기자  사진=권욱 기자': 'Jeongmunyeong gija sajin - Kwon Uk',
  '정상훈 기자': 'Jung Sang-Hun',
  '정상훈 기자,도혜원 기자': 'Jung Sang-Hun, Do Hye-Won',
  '정상훈 기자,송종호 기자': 'Jung Sang-Hun, Song Jong-Ho',
  '정영현 기자': 'Jung Yeong-Hyeon',
  '정용택 IBK투자증권 리서치센터 수석연구위원': 'Jung Yong-Taek IBKTu Ja-Jeung-Gwon Riseochisenteo Suseokyeonguwiwon',
  '정유나 기자': 'Jung Yu-Na',
  '정유나 기자,이유진 기자': 'Jung Yu-Na, Lee Yu-Jin',
  '정유민 기자': 'Jung Yu-Min',
  '정유민 기자,강동헌 기자': 'Jung Yu-Min, Kang Dong-Heon',
  '정유민 기자,윤지영 기자': 'Jung Yu-Min, Yoon Ji-Yeong',
  '정혜진 기자': 'Jung Hye-Jin',
  '정혜진 기자,박시은 기자': 'Jung Hye-Jin, Park Si-Eun',
  '제주=김윤수 기자': 'Jeju - Kim Yun-Su',
  '제주=정혜진 기자': 'Jeju - Jung Hye-Jin',
  '조상인 미술전문기자': 'Cho Sang-In Mi Sul-Jeon-Mun',
  '조수연 기자': 'Cho Su-Yeon',
  '조양준 기자': 'Cho Yang-Jun',
  '조양준 기자,장문항 기자': 'Cho Yang-Jun, Jang Mun-Hang',
  '조용구 신영증권 리서치센터 연구위원': 'Cho Yong-Gu Shin Yeong-Jeung-Gwon Riseochisenteo Yeon Gu-Wi-Won',
  '조윤진 기자': 'Cho Yun-Jin',
  '조윤진 기자,김우보 기자': 'Cho Yun-Jin, Kim U-Bo',
  '조윤진 기자,양지혜 기자': 'Cho Yun-Jin, Yang Ji-Hye',
  '조지원 기자': 'Cho Ji-Won',
  '조지원 기자,변수연 기자': 'Cho Ji-Won, Byun Su-Yeon',
  '조태형 기자': 'Cho Tae-Hyeong',
  '주재현 기자': 'Joo Jae-Hyeon',
  '주재현 기자,박신원 기자,김혜란 기자': 'Joo Jae-Hyeon, Park Sin-Won, Kim Hye-Ran',
  '주재현 기자,이승배 기자': 'Joo Jae-Hyeon, Lee Seung-Bae',
  '주재현 기자,전희윤 기자': 'Joo Jae-Hyeon, Jeon Hui-Yun',
  '주재현 기자,조윤진 기자': 'Joo Jae-Hyeon, Cho Yun-Jin',
  '진도=박지훈 기자': 'Jindo - Park Ji-Hun',
  '진동영 기자': 'Jin Dong-Yeong',
  '진동영 기자,강도림 기자': 'Jin Dong-Yeong, Kang Do-Rim',
  '진동영 기자,도혜원 기자': 'Jin Dong-Yeong, Do Hye-Won',
  '진동영 기자,마가연 기자': 'Jin Dong-Yeong, Ma Ga-Yeon',
  '진동영 기자,이승령 기자': 'Jin Dong-Yeong, Lee Seung-Ryeong',
  '진주=박종완 기자': 'Jinju - Park Jong-Wan',
  '창원=박종완 기자': 'Changwon - Park Jong-Wan',
  '채민석 기자': 'Chae Min-Seok',
  '채민석 기자,김선영 기자': 'Chae Min-Seok, Kim Seon-Yeong',
  '채민석 기자,마가연 기자': 'Chae Min-Seok, Ma Ga-Yeon',
  '채민석 기자,이유진 기자': 'Chae Min-Seok, Lee Yu-Jin',
  '채민석 기자,정유나 기자': 'Chae Min-Seok, Jung Yu-Na',
  '채민석 기자,황동건 기자': 'Chae Min-Seok, Hwang Dong-Geon',
  '천민아 기자': 'Chun Min-A',
  '천안=김현상 기자': 'Cheonan - Kim Hyeon-Sang',
  '천안=박희윤 기자': 'Cheonan - Park Hui-Yun',
  '청주=박희윤 기자': 'Cheongju - Park Hui-Yun',
  '최성욱 기자': 'Choi Seong-Uk',
  '최수문 선임기자': 'Choi Su-Mun (Senior Reporter)',
  '최형욱 논설위원': 'Choi Hyeong-Uk (Editorial Writer)',
  '충주=박희윤 기자': 'Chungju - Park Hui-Yun',
  '충주=최성욱 기자': 'Chungju - Choi Seong-Uk',
  '충칭=김광수 특파원': 'Chungching - Kim Gwang-Su (Correspondent)',
  '쿠알라룸푸르=박창규 기자': 'Kualrarumpureu - Park Chang-Gyu',
  '태안=박희윤 기자': 'Taean - Park Hui-Yun',
  '통영=박종완 기자': 'Tongyeong - Park Jong-Wan',
  '파주=이경환 기자': 'Paju - Lee Gyeong-Hwan',
  '판교=박효정 기자': 'Pangyo - Park Hyo-Jeong',
  '평택=손대선 기자': 'Pyeongtaek - Son Dae-Seon',
  '포천=이경환 기자': 'Pocheon - Lee Gyeong-Hwan',
  '포항=손성락 기자': 'Pohang - Son Seong-Rak',
  '하남=이경환 기자': 'Hanam - Lee Gyeong-Hwan',
  '하노이=박창규 기자': 'Hanoi - Park Chang-Gyu',
  '한동훈 기자': 'Han Dong-Hun',
  '한동훈 기자,김혜란 기자': 'Han Dong-Hun, Kim Hye-Ran',
  '한동훈 기자,박신원 기자': 'Han Dong-Hun, Park Sin-Won',
  '한동훈 기자,박신원 기자,김혜란 기자': 'Han Dong-Hun, Park Sin-Won, Kim Hye-Ran',
  '한동훈 기자,서민우 기자': 'Han Dong-Hun, Seo Min-U',
  '한민구 기자': 'Han Min-Gu',
  '한민구 기자,이정민 기자': 'Han Min-Gu, Lee Jeong-Min',
  '한민구 기자,인천=안재균 기자': 'Han Min-Gu, Incheon - Ahn Jae-Gyun',
  '한영일 논설위원': 'Han Yeong-Il (Editorial Writer)',
  '함평=박지훈 기자': 'Hampyeong - Park Ji-Hun',
  '합천=박종완 기자': 'Hapcheon - Park Jong-Wan',
  '허진 기자': 'Heo Jin',
  '현수아 기자': 'Hyeon Su-A',
  '홍병문 논설위원': 'Hong Byeong-Mun (Editorial Writer)',
  '홍성=박희윤 기자': 'Hongseong - Park Hui-Yun',
  '화순=박지훈 기자': 'Hwasun - Park Ji-Hun',
  '황동건 기자': 'Hwang Dong-Geon',
  '황정원 기자': 'Hwang Jeong-Won',
};

/**
 * 한글 직책 → 영어 직책 매핑
 */
export const TITLE_MAP: Record<string, string> = {
  '특파원': 'Correspondent',
  '기자': 'Reporter',
  '선임기자': 'Senior Reporter',
  '부장': 'Editor',
  '차장': 'Deputy Editor',
  '팀장': 'Team Leader',
  '전문기자': 'Specialist Reporter',
  '의료전문기자': 'Medical Correspondent',
  '객원기자': 'Contributing Writer',
  '에디터': 'Editor',
  '편집위원': 'Editorial Board Member',
  '논설위원': 'Editorial Writer',
  '논설실장': 'Editorial Director',
};

/**
 * 지역명 → 영어 지역명 매핑
 */
export const LOCATION_MAP: Record<string, string> = {
  // 해외
  '워싱턴': 'Washington',
  '뉴욕': 'New York',
  '베이징': 'Beijing',
  '도쿄': 'Tokyo',
  '런던': 'London',
  '상하이': 'Shanghai',
  '홍콩': 'Hong Kong',
  '브뤼셀': 'Brussels',
  '파리': 'Paris',
  '실리콘밸리': 'Silicon Valley',
  'LA': 'Los Angeles',
  '닝보': 'Ningbo',
  '충칭': 'Chungching',

  // 국내
  '수원': 'Suwon',
  '부산': 'Busan',
  '대구': 'Daegu',
  '인천': 'Incheon',
  '광주': 'Gwangju',
  '대전': 'Daejeon',
  '울산': 'Ulsan',
  '세종': 'Sejong',
  '용인': 'Yongin',
  '성남': 'Seongnam',
  '고양': 'Goyang',
  '파주': 'Paju',
  '평택': 'Pyeongtaek',
};
